# Generated by Django 3.2.14 on 2023-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_addon',
            name='createdby',
            field=models.CharField(default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
