# Generated by Django 3.2.14 on 2023-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0002_user_addon_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_addon',
            name='createdby',
            field=models.IntegerField(),
        ),
    ]
