# Generated by Django 3.2.14 on 2023-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0004_zones_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='zid',
            field=models.CharField(max_length=200),
        ),
    ]
