# Generated by Django 3.2.14 on 2023-06-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0005_alter_zones_zid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mtime',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mdate',
            field=models.CharField(max_length=50),
        ),
    ]
