# Generated by Django 3.2.14 on 2023-06-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0007_user_addon_zones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_addon',
            old_name='zones',
            new_name='azones',
        ),
    ]
