# Generated by Django 3.2.14 on 2023-06-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0008_rename_zones_user_addon_azones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='rd',
        ),
    ]
