# Generated by Django 3.2.14 on 2023-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0009_remove_site_rd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='quota',
        ),
        migrations.AddField(
            model_name='user_addon',
            name='quota',
            field=models.IntegerField(default=0),
        ),
    ]
