# Generated by Django 3.2.14 on 2023-06-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0010_auto_20230609_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zones',
            name='assignedto',
        ),
    ]
