# Generated by Django 3.2.14 on 2023-06-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0011_remove_zones_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='etpflow',
            name='itp1ophr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etpflow',
            name='itp2ophr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
