# Generated by Django 3.2.14 on 2023-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0012_auto_20230614_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='etpflow',
            name='itp1c',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etpflow',
            name='itp2c',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
