# Generated by Django 3.2.14 on 2023-06-15 12:20

from django.db import migrations, models
import etp.models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0014_auto_20230614_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='vd',
            field=models.DateTimeField(default=etp.models.site.default_vd),
        ),
    ]
