# Generated by Django 3.2.18 on 2023-06-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0015_site_vd'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='opc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
