# Generated by Django 3.2.18 on 2023-06-28 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etp', '0016_site_opc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='sent', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='user_addon',
            unique_together={('user', 'azones')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
