# Generated by Django 3.2.18 on 2023-06-29 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0017_auto_20230628_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
