# Generated by Django 3.2.14 on 2023-06-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0018_site_ud'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dl',
            field=models.IntegerField(default=0),
        ),
    ]
