# Generated by Django 3.2.14 on 2023-07-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0020_credithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='dnt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='fault',
            unique_together={('site', 'dnt')},
        ),
    ]
