# Generated by Django 3.2.18 on 2023-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0021_auto_20230707_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='dnt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
