# Generated by Django 3.2.18 on 2023-07-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0022_alter_fault_dnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='dnt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
